const assets = [
  { id:'VX-204', name:'Vetor de Campo 204', type:'Veículo terrestre', state:'CA', health:72, vibration:78, temperature:66, hours:1842, criticality:92, status:'attention', last:'Há 2h' },
  { id:'GX-019', name:'Gerador Auxiliar 019', type:'Energia', state:'TX', health:89, vibration:34, temperature:42, hours:621, criticality:74, status:'normal', last:'Há 6 min' },
  { id:'AR-081', name:'Unidade Aérea 081', type:'Plataforma aérea', state:'VA', health:58, vibration:86, temperature:79, hours:2307, criticality:96, status:'critical', last:'Há 1h' },
  { id:'RC-112', name:'Relay de Comunicações 112', type:'Comunicações', state:'WA', health:94, vibration:12, temperature:38, hours:424, criticality:88, status:'normal', last:'Há 1 min' },
  { id:'VX-178', name:'Vetor de Campo 178', type:'Veículo terrestre', state:'FL', health:81, vibration:49, temperature:55, hours:1220, criticality:81, status:'attention', last:'Há 18 min' },
  { id:'GX-028', name:'Gerador Auxiliar 028', type:'Energia', state:'TX', health:67, vibration:71, temperature:69, hours:1961, criticality:69, status:'attention', last:'Há 4h' },
];
const viewMeta={dashboard:['CENTRO DE COMANDO','Visão operacional'],twin:['DIGITAL TWIN','Estado dos ativos'],maintenance:['MAINTAINER','Manutenção inteligente'],readiness:['MISSION READINESS','Prontidão operacional'],review:['DESIGN REVIEW','Validação de alteração'],context:['INTELIGÊNCIA EXTERNA','Contexto público']};
let currentView='dashboard'; let selected=assets[0];
const risk=a=>Math.round((100-a.health)*.5+a.vibration*.2+a.temperature*.15+a.criticality*.15);
const cls=n=>n>=70?'high':n>=45?'medium':'low';
const label=n=>n>=70?'CRÍTICO':n>=45?'ATENÇÃO':'ESTÁVEL';
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function assetRows(list=assets){return list.map(a=>{let r=risk(a);return `<button class="asset-row asset-pick" data-id="${a.id}" style="background:transparent;border-left:0;border-right:0;border-bottom:0;color:inherit;text-align:left;width:100%"><i class="status-dot ${a.status==='critical'?'risk-high':a.status==='attention'?'risk-medium':'risk-low'}"></i><span><span class="asset-name">${a.name}</span><span class="asset-id">${a.id} · ${a.type}</span></span><span class="risk-badge risk-${cls(r)}">${label(r)} ${r}</span><span class="asset-meta">${a.last}</span><span class="readiness-bar"><i style="width:${a.health}%"></i></span></button>`}).join('')}
function dashboard(){let readiness=Math.round(assets.reduce((n,a)=>n+a.health,0)/assets.length);return `<div class="kpi-grid"><div class="card"><div class="kpi-label">PRONTIDÃO DA FROTA</div><div class="kpi-value ${readiness<75?'warn':'good'}">${readiness}%</div><div class="kpi-delta">−3,2% nas últimas 24h</div></div><div class="card"><div class="kpi-label">ATIVOS CRÍTICOS</div><div class="kpi-value bad">${assets.filter(a=>risk(a)>=70).length}</div><div class="kpi-delta">de ${assets.length} ativos monitorados</div></div><div class="card"><div class="kpi-label">MANUTENÇÕES PENDENTES</div><div class="kpi-value warn">04</div><div class="kpi-delta">2 devem ocorrer em até 12h</div></div><div class="card"><div class="kpi-label">COBERTURA DE TELEMETRIA</div><div class="kpi-value good">98,4%</div><div class="kpi-delta">+0,8% desde ontem</div></div></div><div class="dashboard-grid"><article class="card"><div class="section-title"><h2>Ativos por prioridade</h2><span>ATUALIZAÇÃO CONTÍNUA</span></div><div class="asset-list">${assetRows([...assets].sort((a,b)=>risk(b)-risk(a)))}</div></article><article class="card"><div class="section-title"><h2>Eventos recentes</h2><span>ÚLTIMAS 6H</span></div><div class="event-list"><div class="event"><time>10:42</time><strong>Vibração fora da faixa — AR-081</strong><p>Desvio de 22% do padrão esperado no subsistema de propulsão.</p></div><div class="event"><time>09:17</time><strong>Ciclo de inspeção iniciado — VX-204</strong><p>Inspeção preditiva recomendada para as próximas 8 horas.</p></div><div class="event"><time>08:03</time><strong>Alteração revisada — GX-019</strong><p>Filtro de ar aprovado. Sem impacto esperado na disponibilidade.</p></div><div class="event"><time>06:51</time><strong>Telemetria restabelecida — GX-028</strong><p>Janela de conectividade normalizada.</p></div></div></article></div><article class="card wide"><div class="section-title"><h2>Índice de prontidão · últimas 12 horas</h2><span>BASELINE: 82%</span></div><div class="chart">${[76,78,77,80,82,79,80,81,78,75,74,readiness].map(v=>`<i class="bar" data-value="${v}%" style="height:${v}%"></i>`).join('')}</div></article>`}
function twin(){let a=selected;return `<div class="module-header"><div><h2>${a.name}</h2><p>${a.id} · ${a.type} · última telemetria ${a.last}</p></div><span class="risk-badge risk-${cls(risk(a))}">${label(risk(a))} ${risk(a)}</span></div><div class="split"><article class="card"><div class="section-title"><h2>Representação do estado</h2><span>MODELO v0.1</span></div><div class="asset-detail"><div><div class="kpi-label">SAÚDE ESTRUTURAL</div><div class="detail-number">${a.health}%</div></div><div><div class="kpi-label">HORAS DE OPERAÇÃO</div><div class="detail-number">${a.hours.toLocaleString('pt-BR')}h</div></div><div><div class="kpi-label">CRITICIDADE</div><div class="detail-number">${a.criticality}/100</div></div></div>${[['Vibração',a.vibration],['Temperatura',a.temperature],['Integridade de comunicação',a.status==='critical'?81:96]].map(([n,v])=>`<div class="metric-row"><header><span>${n}</span><b>${v}%</b></header><div class="readiness-bar"><i style="width:${v}%"></i></div></div>`).join('')}<div class="reason"><b>Leitura do gêmeo:</b> o modelo combina telemetria atual, histórico de uso e criticidade operacional. A estimativa é explicável e deve ser confirmada por inspeção humana.</div></article><aside class="card"><div class="section-title"><h2>Cenários</h2><span>SIMULAÇÃO</span></div><div class="scenario"><label>Carga operacional<input id="load-range" type="range" min="20" max="100" value="65" /></label><label>Horizonte<select id="horizon"><option>24 horas</option><option>72 horas</option><option>7 dias</option></select></label><button class="button" id="run-scenario">Executar simulação</button></div><div class="impact" id="scenario-result"><div class="kpi-label">RISCO PROJETADO</div><div class="impact-value">${Math.min(99,risk(a)+8)}%</div><div class="kpi-delta">Com carga de 65% nas próximas 24h</div></div></aside></div>`}
function maintenance(){let priorities=[...assets].sort((a,b)=>risk(b)-risk(a));let a=priorities[0];return `<div class="module-header"><div><h2>Fila de manutenção orientada por risco</h2><p>Priorização que combina degradação, criticidade e janela operacional.</p></div><span class="kpi-label">${assets.length} ATIVOS ANALISADOS</span></div><div class="split"><article class="card"><div class="section-title"><h2>Prioridades recomendadas</h2><span>EXPLICÁVEL</span></div>${priorities.map(a=>`<div class="priority"><div><strong>${a.name}</strong><small>${a.id} · ${a.type} · saúde ${a.health}%</small></div><span class="risk-badge risk-${cls(risk(a))}">${risk(a)} pts</span></div>`).join('')}</article><aside class="recommendation"><div class="kpi-label">AÇÃO IMEDIATA</div><h3>Inspecionar ${a.id} nas próximas 4 horas</h3><p>O risco é puxado por vibração (${a.vibration}%), temperatura (${a.temperature}%) e alta criticidade operacional (${a.criticality}/100).</p><p><b>Recomendação:</b> reduzir carga, executar inspeção dirigida e reservar o conjunto de reposição compatível.</p><button class="button secondary" id="schedule-action">Agendar intervenção</button></aside></div>`}
function readiness(){let available=assets.filter(a=>a.health>=70).length;return `<div class="module-header"><div><h2>Prontidão operacional</h2><p>Decisões baseadas em capacidade disponível, risco e impacto de indisponibilidade.</p></div></div><div class="kpi-grid"><div class="card"><div class="kpi-label">CAPACIDADE DISPONÍVEL</div><div class="kpi-value good">${available}/${assets.length}</div><div class="kpi-delta">ativos dentro do limiar mínimo</div></div><div class="card"><div class="kpi-label">RISCO DE MISSÃO</div><div class="kpi-value warn">MODERADO</div><div class="kpi-delta">concentrado em AR-081 e VX-204</div></div><div class="card"><div class="kpi-label">JANELA DE RECUPERAÇÃO</div><div class="kpi-value">18h</div><div class="kpi-delta">com intervenções priorizadas</div></div><div class="card"><div class="kpi-label">RESERVA OPERACIONAL</div><div class="kpi-value">33%</div><div class="kpi-delta">2 ativos aptos para remanejamento</div></div></div><article class="card wide"><div class="section-title"><h2>Simulador de impacto</h2><span>DECISÃO ASSISTIDA</span></div><div class="split"><div class="scenario"><label>Indisponibilizar temporariamente<select id="outage-asset">${assets.map(a=>`<option value="${a.id}">${a.id} — ${a.name}</option>`).join('')}</select></label><label>Duração<select id="outage-duration"><option value="4">4 horas</option><option value="12">12 horas</option><option value="24">24 horas</option></select></label><button class="button" id="calculate-impact">Calcular impacto</button></div><div class="impact" id="impact-result"><div class="kpi-label">PRONTIDÃO PROJETADA</div><div class="impact-value">${Math.round(assets.reduce((s,a)=>s+a.health,0)/assets.length)}%</div><div class="kpi-delta">Selecione um cenário para avaliar a consequência.</div></div></div></article>`}
function review(){return `<div class="module-header"><div><h2>Revisão de alteração técnica</h2><p>Triagem de impacto e rastreabilidade antes de uma mudança entrar em operação.</p></div></div><div class="split"><article class="card"><div class="section-title"><h2>Nova alteração</h2><span>RASCUNHO</span></div><label>Ativo afetado<select id="review-asset">${assets.map(a=>`<option value="${a.id}">${a.id} — ${a.name}</option>`).join('')}</select></label><label>Tipo de alteração<select id="change-type"><option value="component">Substituição de componente</option><option value="configuration">Alteração de configuração</option><option value="load">Aumento de carga operacional</option></select></label><label>Descrição<input id="change-description" placeholder="Ex.: substituir módulo de filtragem por versão B" /></label><button class="button" id="review-change" style="margin-top:16px">Analisar alteração</button></article><aside class="card"><div class="section-title"><h2>Resultado da revisão</h2><span>HUMANO NO LOOP</span></div><div id="review-output"><p class="kpi-delta">Preencha a alteração e execute a análise. O resultado é uma recomendação, não uma autorização automática.</p></div></aside></div>`}
function context(){return `<div class="module-header"><div><h2>Contexto operacional público</h2><p>Fontes oficiais dos EUA usadas como consciência situacional — não como substituto de confirmação local.</p></div><span class="kpi-label">SEM CHAVE DE API</span></div><div class="split"><article class="card"><div class="section-title"><h2>Alertas meteorológicos ativos</h2><span>NOAA / NWS</span></div><label>Estado dos EUA<select id="weather-state"><option value="CA">Califórnia (CA)</option><option value="FL">Flórida (FL)</option><option value="TX">Texas (TX)</option><option value="WA">Washington (WA)</option><option value="VA">Virgínia (VA)</option></select></label><button class="button" id="load-weather" style="margin-top:16px">Consultar alertas ativos</button><div class="review-result" id="weather-output"><p class="kpi-delta">Escolha um estado para consultar alertas ativos diretamente da NOAA/NWS.</p></div></article><article class="card"><div class="section-title"><h2>Atividade sísmica recente</h2><span>USGS · ÚLTIMAS 24H</span></div><button class="button" id="load-quakes">Consultar eventos M4.5+</button><div class="review-result" id="quakes-output"><p class="kpi-delta">A consulta usa o feed GeoJSON público do USGS. Eventos são contexto, não diagnóstico de ativo.</p></div></article></div><article class="card wide"><div class="section-title"><h2>Regra de uso operacional</h2><span>CONTROLE</span></div><div class="reason">Dados públicos externos podem <b>sinalizar contexto</b> e iniciar uma revisão humana. Eles não podem alterar prontidão, liberar ativos, nem criar ordens de manutenção automaticamente. A integração com uma localização real deverá passar por autorização, geofencing e auditoria.</div></article>`}
function render(){let [label,title]=viewMeta[currentView];document.querySelector('#section-label').textContent=label;document.querySelector('#page-title').textContent=title;document.querySelector('#app-content').innerHTML=({dashboard,twin,maintenance,readiness,review,context})[currentView]();bindView()}
function toast(msg){let t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function recordAudit(action, detail){const history=JSON.parse(localStorage.getItem('forge-audit')||'[]');history.unshift({action,detail,at:new Date().toLocaleString('pt-BR')});localStorage.setItem('forge-audit',JSON.stringify(history.slice(0,30)));fetch('/api/audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,detail})}).catch(()=>{})}
function bindView(){
  document.querySelectorAll('.asset-pick').forEach(b=>b.onclick=()=>{selected=assets.find(a=>a.id===b.dataset.id);currentView='twin';setNav();render()});
  const scenario=document.querySelector('#run-scenario'); if(scenario) scenario.onclick=()=>{const load=+document.querySelector('#load-range').value,h=document.querySelector('#horizon').value,value=Math.min(99,risk(selected)+Math.round(load*.18));document.querySelector('#scenario-result').innerHTML=`<div class="kpi-label">RISCO PROJETADO</div><div class="impact-value">${value}%</div><div class="kpi-delta">Carga de ${load}% nas próximas ${h.toLowerCase()} · ${selected.state}</div>`;recordAudit('Simulação',`${selected.id}: carga ${load}% / ${h}`)};
  const schedule=document.querySelector('#schedule-action'); if(schedule) schedule.onclick=()=>{recordAudit('Intervenção pendente',`Inspeção recomendada: ${assets.sort((a,b)=>risk(b)-risk(a))[0].id}`);toast('Intervenção registrada para aprovação humana.')};
  const impact=document.querySelector('#calculate-impact'); if(impact) impact.onclick=()=>{const a=assets.find(x=>x.id===document.querySelector('#outage-asset').value),d=+document.querySelector('#outage-duration').value,avg=Math.round((assets.reduce((s,x)=>s+x.health,0)-a.health*.7)/assets.length);document.querySelector('#impact-result').innerHTML=`<div class="kpi-label">PRONTIDÃO PROJETADA</div><div class="impact-value">${avg}%</div><div class="kpi-delta">${a.id} indisponível por ${d}h. Priorize substituto ou intervenção preventiva.</div>`;recordAudit('Impacto calculado',`${a.id}: indisponibilidade de ${d}h`)};
  const review=document.querySelector('#review-change'); if(review) review.onclick=()=>{const a=assets.find(x=>x.id===document.querySelector('#review-asset').value),type=document.querySelector('#change-type').value,desc=esc(document.querySelector('#change-description').value||'Alteração não detalhada'),attention=type==='load'||risk(a)>70;document.querySelector('#review-output').innerHTML=`<span class="risk-badge risk-${attention?'medium':'low'}">${attention?'ATENÇÃO':'ACEITÁVEL'}</span><div class="review-result"><b>${a.id} · ${desc}</b><div class="check"><i>✓</i><span>Compatibilidade preliminar concluída.</span></div><div class="check"><i>${attention?'!':'✓'}</i><span>${attention?'Requer janela controlada e validação técnica.':'Baixo impacto no cenário atual.'}</span></div><div class="check"><i>⌁</i><span>Próximo passo: revisão e aprovação por responsável técnico.</span></div></div>`;recordAudit('Design review',`${a.id}: ${desc}`)};
  const weather=document.querySelector('#load-weather'); if(weather) weather.onclick=loadWeather;
  const quakes=document.querySelector('#load-quakes'); if(quakes) quakes.onclick=loadQuakes;
}
async function loadWeather(){
  const out=document.querySelector('#weather-output'); const area=document.querySelector('#weather-state').value;
  out.innerHTML='<p class="kpi-delta">Consultando NOAA/NWS…</p>';
  try { const r=await fetch(`/api/context/weather?area=${area}`); if(!r.ok) throw Error(r.status); const d=await r.json(); const items=(d.features||[]).slice(0,4), scoped=assets.filter(a=>a.state===area); const exposure=items.length&&scoped.length?'ATENÇÃO':'SEM EXPOSIÇÃO MAPEADA'; out.innerHTML=`<p class="kpi-label">${d.features?.length||0} ALERTAS ATIVOS · ${exposure}</p><p class="kpi-delta">Ativos no escopo: ${scoped.length?scoped.map(a=>a.id).join(', '):'nenhum ativo simulado'}.</p>`+(items.length?items.map(x=>`<div class="check"><i>!</i><span><b>${esc(x.properties.event||'Alerta')}</b><br><small>${esc(x.properties.headline||'Sem resumo')}</small></span></div>`).join(''):'<p class="good">Nenhum alerta ativo retornado para esta área.</p>'); recordAudit('Contexto NOAA',`${area}: ${d.features?.length||0} alertas; ${scoped.length} ativos no escopo`); }
  catch { out.innerHTML='<p class="warn">Não foi possível consultar a NOAA/NWS agora. Tente novamente.</p>'; }
}
async function loadQuakes(){
  const out=document.querySelector('#quakes-output'); out.innerHTML='<p class="kpi-delta">Consultando feed USGS…</p>';
  try { const r=await fetch('/api/context/earthquakes'); if(!r.ok) throw Error(r.status); const d=await r.json(); const items=(d.features||[]).slice(0,5); out.innerHTML=`<p class="kpi-label">${d.metadata?.count||0} EVENTOS M4.5+ NAS ÚLTIMAS 24H</p>`+items.map(x=>`<div class="check"><i>⌖</i><span><b>M${x.properties.mag} · ${esc(x.properties.place||'Local não informado')}</b><br><small>${new Date(x.properties.time).toLocaleString('pt-BR')}</small></span></div>`).join(''); recordAudit('Contexto USGS',`${d.metadata?.count||0} eventos M4.5+ retornados`); }
  catch { out.innerHTML='<p class="warn">Não foi possível consultar o USGS agora. Tente novamente.</p>'; }
}
function setNav(){document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===currentView))}document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;setNav();render()});document.querySelector('#simulate-button').onclick=()=>{assets.forEach(a=>a.health=Math.max(35,Math.min(99,a.health+Math.round(Math.random()*10-5))));render();toast('Novo ciclo de telemetria simulado.');};document.querySelector('#new-review-button').onclick=()=>{currentView='review';setNav();render()};function clock(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}clock();setInterval(clock,1000);render();
